### ISSUE TITLE
OS X Yosemite Install: No such file or directory: 'requirements.txt'

### ISSUE THREAD

**Issue by frhd** [fritz-hh/OCRmyPDF#115]
I've followed up the OS X installation instructions up until `pip3 install ocrmypdf` and hit a wall:

```
➜  test  pip3 install ocrmypdf
Collecting ocrmypdf
  Using cached ocrmypdf-3.0rc6.tar.gz
    Complete output from command python setup.py egg_info:
    Checking for tesseract >= 3.02.02...
    Found tesseract 3.04.00
    Checking for gs >= 9.14...
    Found gs 9.16
    Checking for unpaper >= 6.1...
    Found unpaper 6.1
    Checking for qpdf >= 5.0.0...
    Found qpdf 5.1.3
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/fm/_0h71wgd4b119f06lpcw2lp00000gn/T/pip-build-cm9j5kyh/ocrmypdf/setup.py", line 177, in <module>
        install_requires = open('requirements.txt').read().splitlines()
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
```

Any ideas?

**Comment by jbarlow83** [comment]
Apologies. I uploaded a new version to fix that.

You may need to run `pip3 --no-cache-dir install ocrmypdf` to bypass the cached copy on your system and ensure it retrieves the new version from PyPI.

**Comment by frhd** [comment]
Awesome @jbarlow83 !
