### ISSUE TITLE
ocrmypdf with incrontab / inotify

### ISSUE THREAD

**Issue by segro21** [fritz-hh/OCRmyPDF#90]
Hi,
this is not realey an issue of ocrmypdf, but I'm trying to get this to work on an samba-share with incrontab /inotify.
I've created a folder and watch activities in this folder with incrontab. That works fine for things like pdftk, but nothing happens on ocrmypdf. Syslog shows the command correct, but then ends.

my incrontab -e
/home/pdfin IN_CLOSE_WRITE  /opt/ocrmypdf/ocrmypdf.sh  $@/$#  $@/out/$#
/home/pdfin/out IN_CLOSE_WRITE /bin/rm $@/../$#
->this works fine for stamping pdfs with logo
/home/stamp IN_CLOSE_WRITE /usr/bin/pdftk $@/$# stamp $@/BB.pdf output $@/out/$#
/home/stamp/out IN_CLOSE_WRITE /bin/rm $@/../$#

Any ideas?

**Comment by Manuel-J** [comment]
Hello,

I have tried the same and can confirm this issue and add some further information.
incrond behaves like cron and runs in a sparse environment. And for me it looks like tesseract cannot resolve its language training data folder within this environment (everything runs smooth if OCRmyPDF is executed interactively):
```
Arguments: -l deu -g /srv/data/kopierer/Scans/test.pdf /srv/data/kopierer/Scans/test_ocr.pdf
Checking if all dependencies are installed
parallel: Warning: $SHELL not set. Using /bin/sh.
Use of uninitialized value $ENV{"HOME"} in concatenation (.) or string at /usr/bin/parallel line 943.
Use of uninitialized value $ENV{"HOME"} in concatenation (.) or string at /usr/bin/parallel line 943.
parallel: Warning: $SHELL not set. Using /bin/sh.
Use of uninitialized value $ENV{"HOME"} in concatenation (.) or string at /usr/bin/parallel line 943.
Use of uninitialized value $ENV{"HOME"} in concatenation (.) or string at /usr/bin/parallel line 943.
--------------------------------
ImageMagick version:
Version: ImageMagick 6.6.9-7 2014-03-06 Q16 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2011 ImageMagick Studio LLC
Features: OpenMP

--------------------------------
GNU Parallel version:
parallel: Warning: $SHELL not set. Using /bin/sh.
Use of uninitialized value $ENV{"HOME"} in concatenation (.) or string at /usr/bin/parallel line 943.
Use of uninitialized value $ENV{"HOME"} in concatenation (.) or string at /usr/bin/parallel line 943.
WARNING: YOU ARE USING --tollef. IF THINGS ARE ACTING WEIRD USE --gnu.
GNU parallel 20121122
Copyright (C) 2007,2008,2009,2010,2011,2012 Ole Tange and Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
GNU parallel comes with no warranty.

Web site: http://www.gnu.org/software/parallel

When using GNU Parallel for a publication please cite:

O. Tange (2011): GNU Parallel - The Command-Line Power Tool,
;login: The USENIX Magazine, February 2011:42-47.

--------------------------------
unpaper version:
0.3
--------------------------------
tesseract version:
tesseract 3.02.02
--------------------------------
python2 version:
Python 2.7.3
--------------------------------
Ghostscript version:
9.05
--------------------------------
Java version:
java version "1.7.0_76"
Java(TM) SE Runtime Environment (build 1.7.0_76-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.76-b04, mixed mode)
--------------------------------
The language "deu" is not supported by tesseract.
Usage:tesseract imagename outputbase [-l lang] [-psm pagesegmode] [configfile...] pagesegmode values are: 0 = Orientation and script detection (OSD$
Exiting...
```

**Comment by fpetry** [comment]
**EDIT:** Solved it by changing the path in the script (see below). Incron is working in "/", and therefore is not able to create som temporary files...

I just tried a similar thing with version 3.1 and ocrmypdf fails while opening a database :-( :

```
Dec  4 16:47:10 notebook incrond[15320]: (six86) CMD (/media/DatenExt/Scanner/ocr.sh /media/DatenExt/Scanner/bbbb.pdf)
Dec  4 16:47:10 notebook ocr.sh: Traceback (most recent call last):
Dec  4 16:47:10 notebook ocr.sh:   File "/usr/local/bin/ocrmypdf", line 11, in <module>
Dec  4 16:47:10 notebook ocr.sh:     sys.exit(run_pipeline())
Dec  4 16:47:10 notebook ocr.sh:   File "/usr/local/lib/python3.5/dist-packages/ocrmypdf/main.py", line 898, in run_pipeline
Dec  4 16:47:10 notebook ocr.sh:     cmdline.run(options)
Dec  4 16:47:10 notebook ocr.sh:   File "/usr/local/lib/python3.5/dist-packages/ruffus/cmdline.py", line 824, in run
Dec  4 16:47:10 notebook ocr.sh:     **appropriate_options)
Dec  4 16:47:10 notebook ocr.sh:   File "/usr/local/lib/python3.5/dist-packages/ruffus/task.py", line 5567, in pipeline_run
Dec  4 16:47:10 notebook ocr.sh:     target_tasks, forcedtorun_tasks)
Dec  4 16:47:10 notebook ocr.sh:   File "/usr/local/lib/python3.5/dist-packages/ruffus/task.py", line 4452, in _pipeline_prepare_to_run
Dec  4 16:47:10 notebook ocr.sh:     job_history = open_job_history(history_file)
Dec  4 16:47:10 notebook ocr.sh:   File "/usr/local/lib/python3.5/dist-packages/ruffus/ruffus_utility.py", line 211, in open_job_history
Dec  4 16:47:10 notebook ocr.sh:     return dbdict.open(history_file, picklevalues=True)
Dec  4 16:47:10 notebook ocr.sh:   File "/usr/local/lib/python3.5/dist-packages/ruffus/dbdict.py", line 363, in open
Dec  4 16:47:10 notebook ocr.sh:     return DbDict(filename, picklevalues)
Dec  4 16:47:10 notebook ocr.sh:   File "/usr/local/lib/python3.5/dist-packages/ruffus/dbdict.py", line 112, in __init__
Dec  4 16:47:10 notebook ocr.sh:     self.con = sqlite3.connect(filename)
Dec  4 16:47:10 notebook ocr.sh: sqlite3.OperationalError: unable to open database file
```

My script:

``` bash
#!/bin/bash
exec 1> >(logger -s -t $(basename $0)) 2>&1

cd /media/DatenExt/Scanner/out/

INFILE=${1##*/} 
OUTFILE=${INFILE%.*}_ocr.pdf
/usr/local/bin/ocrmypdf -l deu $1 /media/DatenExt/Scanner/out/$OUTFILE
```

I suppose it's something with the environment of incron, executing the script seperately works just fine.

**Comment by jbarlow83** [comment]
Yes, it needs to be create that file, so needs a writable CWD. I think. I
will check.

The active project is now jbarlow83/ocrmypdf. Please record any other
issues there. Thanks.
