### ISSUE TITLE
dependecy problem reportlab - allthough installed...

### ISSUE THREAD

**Issue by andreasotto** [fritz-hh/OCRmyPDF#99]
```
# ./OCRmyPDF.sh /home/ao/Leerungstermine189973.PDF /home/ao/test.pdf
Please install the python library reportlab. Exiting...

# apt-get install python-reportlab
python-reportlab ist schon die neueste Version.
```
.. already installed.

Debian 6 squeeze

**Comment by jbarlow83** [comment]
OCRmyPDF v3.0-rc2 needs reportlab >= 3.0

**Comment by Wikinaut** [comment]
Actual problem with 

* Opensuse Tumbleweed
* python-reportlab is installed
* OCRmyPDF still says "Please install the python library reportlab. Exiting...

Having the problem and reading this issue I checked the Tumbleweed reportlab version (2.7-3.3) and 

#### suggest

to change the OCRmyPDF dependency-checker test to "Please install the python library reportlab version >= 3.0". i.e. to notify the user the they must install a correct version.

**Comment by Wikinaut** [comment]
@jbarlow83 pls. can you explain, where the option ``` --pdf-renderer tesseract``` is to be added ? It does not work on a command line of OCRmyPDF

**Comment by jbarlow83** [comment]
Only the new version (a pre-release) supports it:
https://github.com/fritz-hh/OCRmyPDF/releases  version v3.0-rc2.

Or download the source latest from the "master" branch.

**Comment by Wikinaut** [comment]
hmm, one problem is solved (when checking out here, the default branch is v2.x. i changed this now to master) ...

but now I get

```
# sh ./OCRmyPDF.sh -h
Traceback (most recent call last):
  File "/usr/lib64/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/src/OCRmyPDF/ocrmypdf/main.py", line 16, in <module>
    import PyPDF2 as pypdf
ImportError: No module named 'PyPDF2'

```

When I run

```
./OCRmyPDF.sh -h
bash: ./OCRmyPDF.sh: Keine Berechtigung
```

All files and subdirectories belong to the current user.

**Comment by jbarlow83** [comment]
It's a Python 3 package now. Run the installer in the current directory: `pip3 install -e .`

**Comment by Wikinaut** [comment]
oops, while you wrote your answer, I read the readme and did the pip3, but:
```
  FileNotFoundError: [Errno 2] No such file or directory: 'mutool'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /usr/local/src/OCRmyPDF
```

So I have to install this, too. (should it be added to the dependency checks ???)

**Comment by Wikinaut** [comment]
uh, not in Tumbleweed. Have to look for it. (Even Tesseract is easier to install)

**Comment by jbarlow83** [comment]
It's `mupdf-tools`. If it's a pain to get, how is qpdf? Both do the same thing.

Hmm, it looks like some of the dependency checks aren't running in the -rc2 release.

**Comment by Wikinaut** [comment]
It is part of ```mupdf``` in Opensuse

**Comment by Wikinaut** [comment]
Now this is gone, but I have
```
During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/usr/local/src/OCRmyPDF/setup.py", line 167, in <module>
        package='mupdf-tools'
      File "/usr/local/src/OCRmyPDF/setup.py", line 119, in check_external_program
        error_unknown_version(program, package, optional, minimum_version)
    TypeError: error_unknown_version() takes 3 positional arguments but 4 were given
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /usr/local/src/OCRmyPDF

```

**Comment by Wikinaut** [comment]
(post above updated with the complete output)

**Comment by jbarlow83** [comment]
Added a possible fix - do a `git pull`.

**Comment by Wikinaut** [comment]
I was (I am) already on 6e6f918630bba7077ba9a50d75a138767422bce7 . This gives the above error.

**Comment by jbarlow83** [comment]
Apologies, I pushed it to wrong repo. commit 6901550 should now be available.

**Comment by Wikinaut** [comment]
* 6901550065523e575d7d1af609add653b5d2fb91

Different error output:

```
pip3 install -e .
Obtaining file:///usr/local/src/OCRmyPDF
    Complete output from command python setup.py egg_info:
    Checking for tesseract >= 3.02.02...
    Found tesseract 3.04
    Checking for gs >= 9.14...
    Found gs 9.16
    Checking for unpaper >= 6.1...
    Found unpaper 6.2
    Checking for pdfseparate >= 0.29.0...
    Found pdfseparate 0.33.0
    Checking for java >= 1.5.0...
    Found java 1.8.0
    Checking for mutool >= 1.7a...
    Traceback (most recent call last):
      File "/usr/local/src/OCRmyPDF/setup.py", line 117, in check_external_program
        version = version_scrape_regex.search(result).group(1)
    AttributeError: 'NoneType' object has no attribute 'group'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/usr/local/src/OCRmyPDF/setup.py", line 167, in <module>
        package='mupdf-tools'
      File "/usr/local/src/OCRmyPDF/setup.py", line 119, in check_external_program
        error_unknown_version(program, package, optional)
      File "/usr/local/src/OCRmyPDF/setup.py", line 83, in error_unknown_version
        print(unknown_version.format(**locals()), file=sys.stderr)
    KeyError: 'need_version'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /usr/local/src/OCRmyPDF
```

**Comment by jbarlow83** [comment]
Thanks for your patience. Please pull again and it give another shot.

**Comment by Wikinaut** [comment]
uh, now I have
```
pip3 install -e .
Obtaining file:///usr/local/src/OCRmyPDF
    Complete output from command python setup.py egg_info:
    Checking for tesseract >= 3.02.02...
    Found tesseract 3.04
    Checking for gs >= 9.14...
    Found gs 9.16
    Checking for unpaper >= 6.1...
    Found unpaper 6.2
    Checking for pdfseparate >= 0.29.0...
    Found pdfseparate 0.33.0
    Checking for java >= 1.5.0...
    Found java 1.8.0
    Checking for mutool >= 1.7a...
    
    OCRmyPDF requires 'mutool' 1.7a or higher.  Your system has
    'mutool' but we cannot tell what version is installed.  Contact the
    package maintainer.
    
    
    This program is REQUIRED for OCRmyPDF to work.  Installation will abort.
    
    
    On systems with the aptitude package manager (Debian, Ubuntu), try these
    commands:
        sudo apt-get update
        sudo apt-get install mupdf-tools
    
    On RPM-based systems (Red Hat, Fedora), search for instructions on
    installing the RPM for mupdf-tools.
    
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /usr/local/src/OCRmyPDF
```

**Comment by Wikinaut** [comment]
mupdf 1.7-1.3

**Comment by Wikinaut** [comment]
OCRmyPDF is a beast

**Comment by jbarlow83** [comment]
I don't know what to think when Linux distributions make up arbitrary version numbers that don't follow the package's own conventions, as in this case.

I dropped the version requirement to mupdf 1.7.

**Comment by Wikinaut** [comment]
better, but still buggy:

```
   writing manifest file 'ruffus.egg-info/SOURCES.txt'
    running install_lib
    creating /usr/lib/python3.4/site-packages/ruffus
    error: could not create '/usr/lib/python3.4/site-packages/ruffus': Permission denied
    
    ----------------------------------------
Command "/usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip-build-1ekvbx92/ruffus/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-8nnv8idr-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-1ekvbx92/ruffus
```

**Comment by jbarlow83** [comment]
You need to install as sudo or create a virtual environment with pyvenv and
install to that environment. As the error message says it doesn't have
permission to write /usr/local.

**Comment by jbarlow83** [comment]
With a virtual environment:

```
pyvenv venv
source venv/bin/activate
pip3 install -e .
```
